version: '3.8'

services:
  frontend:
    build:
      context: ./Client/numbers-to-words-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5001:5001" 
    environment:
      - ASPNETCORE_URLS=http://+:5001

